- kcards/models/room.py
- kcards/templates/room.html
- kcards/tests/test_models_room.py
- kcards/views/api_rooms.py
- kcards/views/room.py
> Identify rooms by "code" rather than "name"

- kcards/templates/base.html
- kcards/templates/index.html
- kcards/templates/kcards.html
- kcards/templates/room.html
This copies `base.html` from Flask-API and adds a link to the API root.
> Add some branding to the API pages

- Makefile
- app.json
- scripts/generate_sample_data.py
This will let use create samples rooms to make manual testing easier.
> Generate sample data for review apps

- kcards/models/room.py
- kcards/tests/test_models_room.py
- scripts/generate_sample_data.py
> Add colored card arrays to the room model

- Makefile
- kcards/views/api_rooms.py
- tests/fixtures.py
- tests/test_api.py
> Add route to queue cards

- kcards/models/_types.py
- kcards/models/room.py
- kcards/templates/room.html
- kcards/views/api_rooms.py
- kcards/views/index.py
- kcards/views/room.py
- tests/test_api.py
> Return consistent content from room APIs

- kcards/templates/index.html
- kcards/templates/room.html
- kcards/views/api_rooms.py
- kcards/views/room.py
- tests/test_api.py
> Room queue in ui

- Makefile
- kcards/models/room.py
- kcards/tests/test_models_room.py
- kcards/views/api_rooms.py
- scripts/generate_sample_data.py
> Handle multiple room states

- app.json
- kcards/settings.py
- kcards/templates/kcards.html
- kcards/views/_exceptions.py
- kcards/views/api_rooms.py
- kcards/views/index.py
- requirements.txt
- tests/fixtures.py
- tests/test_api.py
> Prevent room creation with the same code

- kcards/models/room.py
- kcards/tests/test_models_room.py
- scripts/generate_sample_data.py
> Swap the behavior of yellow and green

- kcards/templates/index.html
- kcards/views/index.py
> Add a button to join rooms

- kcards/app.py
- kcards/views/__init__.py
- kcards/views/index.py
- kcards/views/rooms.py
> Redirect /rooms to /

- kcards/models/__init__.py
- kcards/models/room.py
- kcards/tests/test_models_room.py
- kcards/views/api_rooms.py
- tests/fixtures.py
> Rename Room.add() to Room.add_card()

- kcards/templates/kcards.html
- kcards/templates/room.html
This is not a long term solution for https://github.com/kcards/kcards/issues/50, but should make development easier in the meantime.
> Refresh the page automatically

- kcards/views/rooms.py
Fixes #52
TIL: https://en.wikipedia.org/wiki/Post/Redirect/Get
> Redirect after POST

- kcards/views/join.py
- tests/test_ui.py
- tests/utils.py
> Strip whitespace from names

- app.json
- kcards/models/room.py
- kcards/tests/test_models_room.py
- kcards/views/api_rooms.py
- requirements/ci.txt
- tests/fixtures.py
- tests/test_api_rooms.py
- tests/test_api_root.py
- tests/utils.py
> Delete older rooms

- kcards/views/join.py
- tests/test_ui.py
> Show an error for empty names

- kcards/models/room.py
- kcards/static/style.css
- kcards/templates/join.html
- kcards/templates/kcards.html
- kcards/templates/options.html
- kcards/templates/room.html
- kcards/tests/test_models_room.py
- kcards/views/api_rooms.py
- kcards/views/index.py
- kcards/views/join.py
- tests/test_api_rooms.py
- tests/test_ui.py
- tests/utils.py
> Strip spaces from room codes

- kcards/templates/room.html
> Show the current speaker

- kcards/templates/room.html
- kcards/views/api_rooms.py
- kcards/views/index.py
- kcards/views/rooms.py
- tests/test_api_rooms.py
- tests/test_ui.py
- tests/utils.py
> Show an error message for unknown rooms

- kcards/models/room.py
- kcards/tests/test_models_room.py
> Force lowercase on codes

- kcards/static/options.js
- kcards/templates/kcards.html
- kcards/templates/options.html
- kcards/views/join.py
- kcards/views/options.py
- tests/test_ui.py
> Add copy room link and name change options

- kcards/templates/options.html
- tests/test_ui.py
> Add a blank back button in the post methods

- kcards/views/_exceptions.py
- kcards/views/api_rooms.py
- tests/test_api_rooms.py
> Handle empty POST to a room queue

- kcards/static/style.css
- kcards/templates/room.html
> Use a fixed footer position

- kcards/templates/room.html
> add tooltips to the buttons in the room

- kcards/settings.py
- kcards/templates/kcards.html
> Add Google Analytics

- Makefile
- Procfile
- app.json
- kcards/static/room.js
- kcards/templates/room.html
- kcards/views/api_rooms.py
- manage.py
- requirements.txt
It's not websockets, but if we like this behavior it should close #102.
> Use a long-running request for better polling

- .travis.yml
- .verchew
- Makefile
- README.md
- kcards/__init__.py
- kcards/models/card.py
- kcards/models/room.py
- kcards/views/api_rooms.py
- kcards/views/join.py
- kcards/views/options.py
- runtime.txt
- setup.py
> Swich to Python 3.6
